version: '3'

services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - vite-front-modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  vite-front-modules: