// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Ebook/ent/user"
	"Ebook/ent/wantlist"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Wantlist is the model entity for the Wantlist schema.
type Wantlist struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WantlistQuery when eager-loading is set.
	Edges        WantlistEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WantlistEdges holds the relations/edges for other nodes in the graph.
type WantlistEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WantlistEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Wantlist) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wantlist.FieldID, wantlist.FieldUserID:
			values[i] = new(sql.NullInt64)
		case wantlist.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Wantlist fields.
func (w *Wantlist) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wantlist.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			w.ID = int(value.Int64)
		case wantlist.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				w.Title = value.String
			}
		case wantlist.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				w.UserID = int(value.Int64)
			}
		default:
			w.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Wantlist.
// This includes values selected through modifiers, order, etc.
func (w *Wantlist) Value(name string) (ent.Value, error) {
	return w.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Wantlist entity.
func (w *Wantlist) QueryUser() *UserQuery {
	return NewWantlistClient(w.config).QueryUser(w)
}

// Update returns a builder for updating this Wantlist.
// Note that you need to call Wantlist.Unwrap() before calling this method if this Wantlist
// was returned from a transaction, and the transaction was committed or rolled back.
func (w *Wantlist) Update() *WantlistUpdateOne {
	return NewWantlistClient(w.config).UpdateOne(w)
}

// Unwrap unwraps the Wantlist entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (w *Wantlist) Unwrap() *Wantlist {
	_tx, ok := w.config.driver.(*txDriver)
	if !ok {
		panic("ent: Wantlist is not a transactional entity")
	}
	w.config.driver = _tx.drv
	return w
}

// String implements the fmt.Stringer.
func (w *Wantlist) String() string {
	var builder strings.Builder
	builder.WriteString("Wantlist(")
	builder.WriteString(fmt.Sprintf("id=%v, ", w.ID))
	builder.WriteString("title=")
	builder.WriteString(w.Title)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", w.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// Wantlists is a parsable slice of Wantlist.
type Wantlists []*Wantlist
